# Generated by Django 4.0.4 on 2022-05-26 13:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(default='', verbose_name='Текст')),
                ('status', models.IntegerField(choices=[(1, 'Активна'), (2, 'Отложена'), (3, 'Выполнена')], default=1, verbose_name='Статус')),
                ('public', models.BooleanField(default=False, verbose_name='Публиная')),
                ('important', models.BooleanField(default=False, verbose_name='Важная')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('execution_time', models.DateTimeField(default='2022-05-27 16:53:30.464028', verbose_name='Срок выполнения')),
                ('authors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='', verbose_name='Текст')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ToDo_models.task')),
            ],
        ),
    ]
