# Generated by Django 4.0.4 on 2022-05-26 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterField(
            model_name='task',
            name='execution_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 27, 18, 44, 48, 690898), verbose_name='Срок выполнения'),
        ),
    ]
